import { Mafs,Coordinates,Point} from "mafs"
import Head from 'next/head'
import Image from 'next/image'
import Navbar from "./components/Navbar"
import { useState } from "react"
export default function Home() {
  const [cordinate, setcordinate] = useState({x:"0",y:"0"});
  const onXChange=(e)=>{
    setcordinate({...cordinate,[e.target.name]:e.target.value})
  }
  const setCords = async (newData)=>{
    console.log("Sending")
    const response = await fetch("./api/hello", {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(newData)
    });
  }
  const handelClick = (e)=>{
    e.preventDefault()
    const newData = {x:parseInt(cordinate.x),y:parseInt(cordinate.y)}
    setCords(newData)
  }
  return (
    <>
      <Head>
        <title>Journey Bot Control</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <div className="flex">
      <div className="mx-10">
        <Mafs height={500} width={500} viewBox={{x: [-5,5], y: [-5, 5]}}>
          <Coordinates.Cartesian y = {{subdivisions:10}} />
          <Point x={0} y={0}  color="red"/>
          <Point x={cordinate.x} y={cordinate.y} color="green"/>
        </Mafs>
      </div>
      <div>
      <div className="mx-6 flex my-4">
        <h6 className="">X:</h6>
        <input type="text" placeholder="Enter the X value" value={cordinate.x} name="x" onChange={onXChange} className="border border-black ml-2"/>
      </div>
      <div className="mx-6 flex my-4">
        <h6 className="">Y:</h6>
        <input type="text" placeholder="Enter the Y value" value={cordinate.y} name="y" onChange={onXChange} className="border border-black ml-2"/>
      </div>
      <div className="mx-12">
      <button type="submit" className="border-2 border-red-600 bg-blue-400 rounded-md" onClick={handelClick}>Set Destination</button>
      </div>
      </div>
      </div>
    </>
  )
}
